config/routes.rb
Rails.application.routes.draw do
  get 'team_members/create'
  get 'team_members/destroy'
  get 'teams/join'
  get 'profiles/show'
  get 'passwords/edit'
  get 'passwords/update'
  get 'passwords/password_params'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
    resource :registration
    resource :session
    resource :new_pasword_reset
    resource :password
    resource :profile, only: [:show]
    resources :events
    post 'join_team', to: 'teams#join'
    resources :teams do
      member do
        delete 'remove_user/:user_id', to: 'teams#remove_user', as: 'remove_user'
        post 'add_user/:user_id', to: 'teams#add_user', as: 'add_user'
      end
    end
    root "main#index"
end
  

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  # Akcja która będzie obsługiwać wyświetlanie profilu użytkownika.
  def show
    @user = current_user
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="container mt-5">
  <h1 class="text-center">Twój Profil</h1>
  <div class="row mt-4">
    <div class="col-md-6 offset-md-3">
      <h3>Informacje o użytkowniku</h3>
      <p>Email: <%= @user.email %></p>
      <p>Rola: <%= @user.role %></p>
      <% if @user.team.present? %>
        <p>Drużyna: <%= @user.team.name %></p>
      <% else %>
        <p>Nieprzypisany do żadnej drużyny</p>
      <% end %>
      <%= link_to "Edytuj hasło", edit_password_path, class: "btn btn-warning" %>
    </div>
  </div>
  <% if @user.role == "admin" %>
    <div class="row mt-4">
      <div class="col-md-12 offset-md-3">
        <h3>Panel Administratora</h3>
        <div style="display: flex; gap: 8px;">
          <%= link_to "Zarządzaj zespołami", teams_path, class: "btn btn-primary" %>
          <%= link_to "Utwórz drużynę", new_team_path, class: "btn btn-success" %>
          <%= link_to "Zarządzaj spotkaniami", events_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row mt-4">
      <div class="col-md-6 offset-md-3">
        <h3>Zapisz się do drużyny</h3>
        <%= form_with(model: @user, url: join_team_path, method: :post) do |form| %>
          <div class="mb-3">
            <%= form.label :team_id, "Wybierz drużynę" %>
            <%= form.collection_select :team_id, Team.all, :id, :name, prompt: "Wybierz drużynę", class: "form-control" %>
          </div>
          <%= form.submit "Zapisz się do drużyny", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>