config/routes.rb
Rails.application.routes.draw do
  get 'team_members/create'
  get 'team_members/destroy'
  get 'teams/join'
  get 'profiles/show'
  get 'passwords/edit'
  get 'passwords/update'
  get 'passwords/password_params'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
    resource :registration
    resource :session
    resource :new_pasword_reset
    resource :password
    resource :profile, only: [:show]
    resources :events
    post 'join_team', to: 'teams#join'
    resources :teams do
      member do
        delete 'remove_user/:user_id', to: 'teams#remove_user', as: 'remove_user'
        post 'add_user/:user_id', to: 'teams#add_user', as: 'add_user'
      end
    end
    root "main#index"
end
  

app/models/event.rb
class Event < ApplicationRecord
    validate :different_teams
  
    def different_teams
      errors.add(:base, "Drużyny biorące udział w spotkaniu muszą być różne") if name_first_team == name_second_team
    end
  end
  

app/controllers/events_controller.rb
class EventsController < ApplicationController
    # Filtr sprawdzający, czy użytkownik jest zalogowany
    before_action :authenticate_user!

    # Filtr sprawdzający, czy użytkownik ma uprawnienia administratora
    before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
    
    # Filtr ustawiający zmienną @event dla określonych akcji
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # Akcja wyświetlająca listę wydarzeń
    def index
      @events = Event.order(date: :desc)
      @user = current_user
    end
    
    # Akcja wyświetlająca pojedyncze wydarzenie
    def show
    end

    # Akcja tworząca nowe wydarzenie
    def new
      @event = Event.new
    end
    
    # Akcja zapisująca nowe wydarzenie do bazy danych
    def create
      @event = Event.new(event_params)
  
      if @event.save
        redirect_to @event, notice: "Wydarzenie zostało pomyślnie utworzone."
      else
        render :new
      end
    end
    
    # Akcja wyświetlająca formularz edycji wydarzenia
    def edit
    end
  
    # Akcja zapisująca zmiany w edytowanym wydarzeniu
    def update
      if @event.update(event_params)
        redirect_to @event, notice: "Wydarzenie zostało pomyślnie zaktualizowane."
      else
        render :edit
      end
    end

    # Akcja usuwająca wydarzenie
    def destroy
        @event = Event.find(params[:id])
        @event.delete
        redirect_to events_path, notice: "Wydarzenie zostało pomyślnie usunięte."
    end
  
    private
    
    # Ustawienie zmiennej @event na podstawie przekazanego identyfikatora
    def set_event
      @event = Event.find(params[:id])
    end
    
    # Parametry akcji create i update
    def event_params
      params.require(:event).permit(:name_first_team, :name_second_team, :date, :team_first_score, :team_second_score)
    end
    
    # Sprawdzenie uprawnień administratora
    def require_admin
      redirect_to root_path, alert: "Brak uprawnień" unless current_user.role == "admin"
    end
  end
  

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true, class: "mt-3") do |form| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Błąd!</h4>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label "Nazwa pierwszej drużyny", class: "form-label" %>
    <%= form.collection_select :name_first_team, Team.all, :name, :name, { prompt: "Wybierz drużynę" }, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label "Nazwa drugiej drużyny", class: "form-label" %>
    <%= form.collection_select :name_second_team, Team.all, :name, :name, { prompt: "Wybierz drużynę" }, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label "Data spotkania", class: "form-label" %>
    <%= form.datetime_field :date, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label "Wynik pierwszego zespołu", class: "form-label" %>
    <%= form.number_field :team_first_score, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label "Wynik drugiego zespołu", class: "form-label" %>
    <%= form.number_field :team_second_score, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Zapisz", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Edytuj spotkanie</h1>
  <%= render "form" %>
  <div class="mt-3">
    <%= link_to "Powrót", events_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/events/index.html.erb
<% if @user.role == "admin" %>
  <div class="container mt-5">
    <h1 class="text-center">Spotkania</h1>
    <%= link_to "Powrót", profile_path, class: "btn btn-secondary" %>
    <%= link_to "Nowe spotkanie", new_event_path, class: "btn btn-primary" %>
    <table class="table table-striped table-bordered mt-2">
      <thead class="thead-dark">
        <tr>
          <th class="text-center align-middle">Nazwa pierwszej drużyny</th>
          <th class="text-center align-middle">Nazwa drugiej drużyny</th>
          <th class="text-center align-middle">Data spotkania</th>
          <th class="text-center align-middle">Wynik pierwszego zespołu</th>
          <th class="text-center align-middle">Wynik drugiego zespołu</th>
          <th class="text-center align-middle">Akcje</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td class="text-center align-middle"><%= event.name_first_team %></td>
            <td class="text-center align-middle"><%= event.name_second_team %></td>
            <td class="text-center align-middle"><%= event.date %></td>
            <td class="text-center align-middle"><%= event.team_first_score %></td>
            <td class="text-center align-middle"><%= event.team_second_score %></td>
            <td class="text-center align-middle">
              <div class="d-flex flex-column align-items-center">
                <%= link_to "Szczegóły", event, class: "btn btn-primary btn-sm btn-block mb-2" %>
                <%= link_to "Edytuj", edit_event_path(event), class: "btn btn-warning btn-sm btn-block mb-2" %>
                <%= form_with(model: event, method: :delete, url: event_path(event), data: { confirm: "Are you sure?" }) do |form| %>
                  <%= form.submit "Usuń", class: "btn btn-danger btn-sm btn-block" %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="container mt-5">
    <h1 class="text-center">Spotkania</h1>
    <%= link_to "Powrót", profile_path, class: "btn btn-secondary" %>
    <table class="table table-striped table-bordered mt-2">
      <thead class="thead-dark">
        <tr>
          <th class="text-center align-middle">Nazwa pierwszej drużyny</th>
          <th class="text-center align-middle">Nazwa drugiej drużyny</th>
          <th class="text-center align-middle">Data spotkania</th>
          <th class="text-center align-middle">Wynik pierwszego zespołu</th>
          <th class="text-center align-middle">Wynik drugiego zespołu</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td class="text-center align-middle"><%= event.name_first_team %></td>
            <td class="text-center align-middle"><%= event.name_second_team %></td>
            <td class="text-center align-middle"><%= event.date %></td>
            <td class="text-center align-middle"><%= event.team_first_score %></td>
            <td class="text-center align-middle"><%= event.team_second_score %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/events/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mb-4">Nowe spotkanie</h1>
      <%= render "form" %>
      <%= link_to "Powrót", events_path, class: "btn btn-secondary mt-3" %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container mt-5">
  <% if notice.present? %>
    <div id="notice" class="alert alert-info">
      <%= notice %>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Szczegóły spotkania</h5>
      <p class="card-text">
        <strong>Nazwa pierwszej drużyny:</strong>
        <%= @event.name_first_team %>
      </p>
      <p class="card-text">
        <strong>Nazwa drugiej drużyny:</strong>
        <%= @event.name_second_team %>
      </p>
      <p class="card-text">
        <strong>Data spotkania:</strong>
        <%= @event.date %>
      </p>
      <p class="card-text">
        <strong>Wynik pierwszego zespołu:</strong>
        <%= @event.team_first_score %>
      </p>
      <p class="card-text">
        <strong>Wynik drugiego zespołu:</strong>
        <%= @event.team_second_score %>
      </p>
      <%= link_to "Edytuj", edit_event_path(@event), class: "btn btn-primary" %>
      <%= link_to "Powrót", events_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>