config/routes.rb
Rails.application.routes.draw do
  get 'team_members/create'
  get 'team_members/destroy'
  get 'teams/join'
  get 'profiles/show'
  get 'passwords/edit'
  get 'passwords/update'
  get 'passwords/password_params'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
    resource :registration
    resource :session
    resource :new_pasword_reset
    resource :password
    resource :profile, only: [:show]
    resources :events
    post 'join_team', to: 'teams#join'
    resources :teams do
      member do
        delete 'remove_user/:user_id', to: 'teams#remove_user', as: 'remove_user'
        post 'add_user/:user_id', to: 'teams#add_user', as: 'add_user'
      end
    end
    root "main#index"
end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Liga Akademicka PRz - portal rozgrywek sportowych</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      .custom-margin-right {
        margin-right: 8px;
      }
      .custom-alert {
        margin-top: 50px;
        width: 300px;
      }
    </style>
  </head>
  <nav class="navbar navbar-expand-md navbar-light bg-light px-2">
    <a class="navbar-brand">Liga Akademicka PRz - portal rozgrywek sportowych</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item my-2 my-lg-0 d-flex">
          <% if user_signed_in? %>
            <%= link_to "Spotkania", events_path, class: "nav-link custom-margin-right #{"active" if current_page?(events_path)}" %>
            <%= link_to "Profil", profile_path, class: "nav-link custom-margin-right #{"active" if current_page?(profile_path)}" %>
            <%= button_to "Wyloguj", session_path, method: :delete, class: "nav-link" %>
          <% else %>
            <%if current_page?(new_registration_path) || current_page?(new_session_path)%>
              <%= link_to "Zarejestruj", new_registration_path, class: "nav-link custom-margin-right #{"active" if current_page?(new_registration_path)}" %>
              <%= link_to "Zaloguj", new_session_path, class: "nav-link #{"active" if current_page?(new_session_path)}" %>
            <% else %>
              <%= link_to "Zarejestruj", new_registration_path, class: "nav-link custom-margin-right" %>
              <%= link_to "Zaloguj", new_session_path, class: "nav-link" %>
            <%end%>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <body class="d-flex flex-column ">
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show custom-alert" role="alert" style="position: absolute; top: 7.5%; left: 50%; transform: translate(-50%, -50%); z-index: 1000;">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show custom-alert" role="alert" style="position: absolute; top: 7.5%; left: 50%; transform: translate(-50%, -50%); z-index: 1000;">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="mt-5">
      <%= yield %>
    </div>
  </body>
</html>